### ISSUE TITLE
batch_size problem

### ISSUE THREAD

**Issue by sydney72380** [MediaBrain-SJTU/MVFA-AD#10]
代码默认的batch_size是1，但是论文里说用的是16，改成batch_size=16，会报错：
File "/home/cwj/sata1/work/paper/medical/code/MVFA-AD-main/CLIP/adapter.py", line 81, in forward
out_attn = out_attn + attn_out[i][0, 0, 1:].view(H, H)报错IndexError: list index out of range，
有人遇到过吗？

**Comment by 7HHHHH** [comment]
请问您是如何解决的？

**Comment by sydney72380** [comment]
好像是哪一步维度不太对，调整一下就好了，具体的有点忘了。你一步步断点跟一下，我印象中好像不难解决

**Comment by tobeaTrueman** [comment]
> 请问您是如何解决的？
兄弟 你就解决了吗？
