### ISSUE TITLE
与VAND中的工作的区别

### ISSUE THREAD

**Issue by leejq666** [MediaBrain-SJTU/MVFA-AD#2]
您好！您这篇工作在AS训练过程中使用了像素级注释，但是VAND中的工作如 April-GAN 貌似没有使用像素级注释？

**Comment by chaoqinhuang** [comment]
April-GAN在VAND比赛中，使用的是MVTec AD的像素级注释进行训练
在我们论文的实验中，我们调整April-GAN的训练数据，使其与我们的方法使用的训练数据对齐

**Comment by leejq666** [comment]
okok非常感谢您的回复

**Comment by chaoqinhuang** [comment]
相乘后保持原维度，与文本特征进行比较前的特征维数一致

**Comment by chaoqinhuang** [comment]
矩阵叉乘，结果是一个G*2的矩阵

**Comment by leejq666** [comment]
谢谢，了解了！
